const product = [
    {
        id: 1,
        name: "Nike Air Jordan",
        description: "NIKE AIR JORDAN 1 WMNS RETRO HIGH PINE GREEN ЗЕЛЕНЫЕ КОЖА ЖЕНСКИЕ (AR19003)",
        img: "https://restokk.ru/images/catalog/19003/krossovki-zhenskie-nike-air-jordan-1-wmns-retro-high-pine-green-black-pine-green-white-gym-red-1.jpg?v=824",
        price: 1200,
        discouned: 50,
        isSaled: false,
    },
    {
        id: 2,
        name: "Jordan Womans",
        description: "Nike Jordan Women's Shoes Air Jordan 1 Mid SE Light Club CW1140-100",
        img: "https://outmaxshop.ru/components/com_jshopping/files/img_products/906/nike-air-jordan-4-retro-906-1.jpg",
        price: 2300,
        discouned: 30,
        isSaled: true,
    },
    {
        id: 3,
        name: "Nike's Senior",
        description: "Nike’s Senior Designer Explains What Went into the New Air Jordan XXXI",
        img: "https://media.architecturaldigest.com/photos/57a11cbeb6c434ab487bc26b/1:1/w_774,h_774,c_limit/nikes-senior-designer-explains-what-went-into-new-air-jordan-01.png",
        price: 1800,
        discouned: 20,
        isSaled: false,
    },
    {
        id: 4,
        name: "Woman's Jordan Shous",
        description: "Nike Shous for Womans with hight quality, moders design and fashion with cheap price and accesible for all",
        img: "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/77d72b06-4c1a-4098-aa37-2d2e69365dd7/AIR+JORDAN+1+LOW+SE.png",
        price: 1000,
        discouned: 10,
        isSaled: false,
    },
    {
        id: 5,
        name: "Nike Air Jordan",
        description: "КРОССОВКИ NIKE AIR JORDAN 1 LOW ЦВЕТ ЧЕРНЫЙ",
        img: "https://cdn1.ozone.ru/s3/multimedia-v/6833461603.jpg",
        price: 1200,
        discouned: 50,
        isSaled: false,
    },
    {
        id: 6,
        name: "Nike Air Jordan",
        description: "NIKE AIR JORDAN 1 LOW SE GS ‘CONCORD’ БЕЛЫЕ С ЧЕРНЫМ КОЖАНЫЕ ЛАКИРОВАННЫЕ МУЖСКИЕ-ЖЕНСКИЕ (40-44)",
        img: "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/849566c0-f04e-4742-96f1-8f6ca677f246/AIR+JORDAN+1+RETRO+HIGH+OG.png",
        price: 1900,
        discouned: 0,
        isSaled: false,
    },
    {
        id: 7,
        name: "AIR JORDAN 38 ",
        description: "НОВЕЙШИЕ КРОССОВКИ 2023 Г. В ЛИНЕЙКЕ МАЙКЛА ДЖОРДАНА",
        img: "https://nikefans.ru/wp-content/uploads/2023/07/air-jordan-38-05.jpg",
        price: 1200,
        discouned: 50,
        isSaled: false,
    },
]